"""
HR Analytics Data Generator
Company: TalentBridge Solutions
Generates realistic SQL INSERT statements for 1,000 employees
with planted real-world HR problems for Power BI analysis.
"""

import random
from datetime import date, timedelta
from faker import Faker

fake = Faker()
random.seed(42)  # Makes results reproducible

output_lines = []

def sql(line):
    output_lines.append(line)

def rand_date(start, end):
    delta = end - start
    return start + timedelta(days=random.randint(0, delta.days))

def fmt(d):
    return d.strftime("'%Y-%m-%d'")

# ─────────────────────────────────────────────
# 1. DEPARTMENTS (6 rows)
# ─────────────────────────────────────────────
sql("-- ============================================================")
sql("-- TalentBridge Solutions — HR Analytics Database")
sql("-- Generated by: generate_hr_data.py")
sql("-- Total employees: 1,000 | Years: 2020–2024")
sql("-- ============================================================\n")
sql("USE hr_analytics;\n")
sql("-- ------------------------------------------------------------")
sql("-- DEPARTMENTS")
sql("-- ------------------------------------------------------------")
sql("INSERT INTO departments (department_id, department_name, location, manager_id) VALUES")
sql("(1, 'Engineering',       'Cairo',       NULL),")
sql("(2, 'Sales',             'Cairo',       NULL),")
sql("(3, 'Human Resources',   'Alexandria',  NULL),")
sql("(4, 'Finance',           'Cairo',       NULL),")
sql("(5, 'Marketing',         'Giza',        NULL),")
sql("(6, 'Customer Support',  'Alexandria',  NULL);\n")

# ─────────────────────────────────────────────
# 2. JOBS (12 rows)
# ─────────────────────────────────────────────
sql("-- ------------------------------------------------------------")
sql("-- JOBS")
sql("-- ------------------------------------------------------------")
sql("INSERT INTO jobs (job_id, job_title, min_salary, max_salary, job_level) VALUES")
jobs = [
    (1,  'Software Engineer',        4000,  9000,  'Mid'),
    (2,  'Senior Software Engineer', 7000,  14000, 'Senior'),
    (3,  'Sales Representative',     2500,  5500,  'Junior'),
    (4,  'Sales Manager',            5000,  10000, 'Manager'),
    (5,  'HR Specialist',            2500,  5000,  'Mid'),
    (6,  'HR Manager',               5000,  9000,  'Manager'),
    (7,  'Financial Analyst',        3500,  7000,  'Mid'),
    (8,  'Finance Manager',          6000,  11000, 'Manager'),
    (9,  'Marketing Specialist',     3000,  6000,  'Mid'),
    (10, 'Marketing Manager',        5500,  10000, 'Manager'),
    (11, 'Support Specialist',       2000,  4500,  'Junior'),
    (12, 'Engineering Manager',      9000,  16000, 'Manager'),
]
job_rows = []
for j in jobs:
    job_rows.append(f"({j[0]}, '{j[1]}', {j[2]}.00, {j[3]}.00, '{j[4]}')")
sql(",\n".join(job_rows) + ";\n")

# ─────────────────────────────────────────────
# 3. EMPLOYEES (1,000 rows)
# ─────────────────────────────────────────────

# Department → job mapping
dept_jobs = {
    1: [1, 2, 12],   # Engineering
    2: [3, 4],        # Sales
    3: [5, 6],        # HR
    4: [7, 8],        # Finance
    5: [9, 10],       # Marketing
    6: [11],          # Support
}

# Department size distribution (totals 1000)
dept_sizes = {1: 280, 2: 200, 3: 80, 4: 120, 5: 150, 6: 170}

# Cities by department
dept_cities = {
    1: 'Cairo', 2: 'Cairo', 3: 'Alexandria',
    4: 'Cairo', 5: 'Giza',  6: 'Alexandria'
}

# Employment types
emp_types = ['Full-time', 'Full-time', 'Full-time', 'Part-time', 'Contract']

# --- Build employee pool ---
employees = []
emp_id = 1

# We'll assign managers after building the pool
# First pass: assign dept, job, hire_date, gender, status

for dept_id, count in dept_sizes.items():
    for i in range(count):
        gender = random.choices(['Male', 'Female'], weights=[55, 45])[0]

        # Plant problem: Engineering has younger/less tenured employees (higher attrition)
        if dept_id == 1:
            hire_start = date(2020, 1, 1)
            hire_end   = date(2024, 6, 1)
        else:
            hire_start = date(2019, 1, 1)
            hire_end   = date(2024, 6, 1)

        hire_date  = rand_date(hire_start, hire_end)
        birth_date = hire_date - timedelta(days=random.randint(365*22, 365*45))

        job_id = random.choice(dept_jobs[dept_id])

        # Manager jobs are rare (1 per dept roughly)
        manager_job_ids = [4, 6, 8, 10, 12]
        if job_id in manager_job_ids and i > 0:
            job_id = dept_jobs[dept_id][0]  # bump back to non-manager

        emp_type = random.choices(emp_types, weights=[60,10,10,10,10])[0]

        # Status: most active, some terminated (will link to attrition later)
        # Engineering has higher termination rate (planted problem)
        if dept_id == 1:
            status = random.choices(['Active', 'Terminated'], weights=[78, 22])[0]
        elif dept_id == 6:
            status = random.choices(['Active', 'Terminated'], weights=[85, 15])[0]
        else:
            status = random.choices(['Active', 'Terminated'], weights=[92, 8])[0]

        employees.append({
            'employee_id':     emp_id,
            'first_name':      fake.first_name_male() if gender == 'Male' else fake.first_name_female(),
            'last_name':       fake.last_name(),
            'gender':          gender,
            'birth_date':      birth_date,
            'hire_date':       hire_date,
            'email':           f"emp{emp_id}@talentbridge.com",
            'phone':           fake.numerify('+20 1## ### ####'),
            'department_id':   dept_id,
            'job_id':          job_id,
            'manager_id':      None,  # assigned below
            'employment_type': emp_type,
            'status':          status,
            'country':         'Egypt',
            'city':            dept_cities[dept_id],
        })
        emp_id += 1

# Assign managers: first employee per dept becomes the manager
dept_manager_map = {}
for e in employees:
    d = e['department_id']
    if d not in dept_manager_map:
        dept_manager_map[d] = e['employee_id']
        e['job_id'] = dept_jobs[d][-1]  # manager job

# Plant problem: one bad manager in Engineering (manager_id = dept_manager_map[1])
# Their team will have extra attrition planted later
bad_manager_id = dept_manager_map[1]

# Assign manager_id to all non-manager employees
for e in employees:
    if e['employee_id'] != dept_manager_map[e['department_id']]:
        e['manager_id'] = dept_manager_map[e['department_id']]

sql("-- ------------------------------------------------------------")
sql("-- EMPLOYEES (1,000 rows — split into chunks of 100)")
sql("-- ------------------------------------------------------------")

emp_rows = []
for e in employees:
    mgr = str(e['manager_id']) if e['manager_id'] else 'NULL'
    emp_rows.append(
        f"({e['employee_id']}, '{e['first_name']}', '{e['last_name']}', '{e['gender']}', "
        f"{fmt(e['birth_date'])}, {fmt(e['hire_date'])}, '{e['email']}', '{e['phone']}', "
        f"{e['department_id']}, {e['job_id']}, {mgr}, '{e['employment_type']}', "
        f"'{e['status']}', '{e['country']}', '{e['city']}')"
    )

def chunk_insert(table_header, rows, chunk_size=100):
    for i in range(0, len(rows), chunk_size):
        chunk = rows[i:i+chunk_size]
        sql(table_header)
        sql(",\n".join(chunk) + ";\n")

chunk_insert(
    "INSERT INTO employees (employee_id, first_name, last_name, gender, birth_date, hire_date,\n"
    "    email, phone, department_id, job_id, manager_id, employment_type, status, country, city) VALUES",
    emp_rows
)

# ─────────────────────────────────────────────
# 4. SALARIES
# ─────────────────────────────────────────────

# Job salary base ranges
job_salary_map = {j[0]: (j[2], j[3]) for j in jobs}

sql("-- ------------------------------------------------------------")
sql("-- SALARIES (~1,400 rows — some employees have raise history)")
sql("-- ------------------------------------------------------------")

salary_rows = []
salary_id = 1

for e in employees:
    min_s, max_s = job_salary_map[e['job_id']]

    # Plant problem: female employees earn 8–12% less on average
    gender_factor = random.uniform(0.88, 0.95) if e['gender'] == 'Female' else 1.0

    base_salary = round(random.uniform(min_s, max_s) * gender_factor, 2)
    start = e['hire_date']

    # Plant problem: salary compression — long-tenured employees get fewer raises
    years_employed = (date(2024, 12, 31) - e['hire_date']).days / 365
    if years_employed > 3:
        num_raises = random.choices([0, 1], weights=[40, 60])[0]  # compression
    else:
        num_raises = random.choices([0, 1, 2], weights=[50, 35, 15])[0]

    if num_raises == 0:
        # Single salary record, still active
        end = 'NULL'
        salary_rows.append(
            f"({e['employee_id']}, {base_salary}, {fmt(start)}, {end}, 'Monthly', 'USD')"
        )
    else:
        # Multiple salary records — raise history
        current_salary = base_salary
        current_start  = start
        for r in range(num_raises):
            raise_date = current_start + timedelta(days=random.randint(365, 730))
            if raise_date >= date(2024, 12, 31):
                break
            salary_rows.append(
                f"({e['employee_id']}, {current_salary}, {fmt(current_start)}, {fmt(raise_date - timedelta(days=1))}, 'Monthly', 'USD')"
            )
            # Raise amount: 5–15%
            current_salary = round(current_salary * random.uniform(1.05, 1.15), 2)
            current_start  = raise_date

        # Final (current) salary
        salary_rows.append(
            f"({e['employee_id']}, {current_salary}, {fmt(current_start)}, NULL, 'Monthly', 'USD')"
        )

chunk_insert(
    "INSERT INTO salaries (employee_id, salary_amount, effective_date, end_date, salary_type, currency) VALUES",
    salary_rows
)

# ─────────────────────────────────────────────
# 5. PERFORMANCE REVIEWS
# ─────────────────────────────────────────────
sql("-- ------------------------------------------------------------")
sql("-- PERFORMANCE REVIEWS (~2,500 rows)")
sql("-- ------------------------------------------------------------")
review_rows = []
review_periods = ['Annual 2020', 'Annual 2021', 'Annual 2022', 'Annual 2023', 'Annual 2024']
review_dates   = {
    'Annual 2020': date(2021, 1, 15),
    'Annual 2021': date(2022, 1, 15),
    'Annual 2022': date(2023, 1, 15),
    'Annual 2023': date(2024, 1, 15),
    'Annual 2024': date(2024, 12, 15),
}
comments_pool = [
    'Consistently meets expectations.',
    'Exceeded targets this quarter.',
    'Needs improvement in communication.',
    'Strong technical skills demonstrated.',
    'Great team player and collaborator.',
    'Missed several key deadlines.',
    'Outstanding performance this year.',
    'Shows potential for leadership.',
    'Performance below expectations.',
    'Reliable and consistent contributor.',
]

for e in employees:
    hire_year = e['hire_date'].year
    reviewer  = dept_manager_map[e['department_id']]

    for period in review_periods:
        period_year = int(period.split()[1])
        if period_year < hire_year:
            continue
        if e['status'] == 'Terminated':
            exit_year = random.randint(min(hire_year + 1, 2024), 2024)
            if period_year > exit_year:
                continue

        # Plant problem: bad manager's team gets lower ratings
        if e['manager_id'] == bad_manager_id:
            rating = round(random.uniform(1.5, 3.5), 1)
        else:
            rating = round(random.uniform(2.5, 5.0), 1)

        # Plant problem: high performers not getting salary increases (mismatch)
        goals_met = 1 if rating >= 3.5 else 0
        comment   = random.choice(comments_pool).replace("'", "''")
        rdate     = review_dates[period] + timedelta(days=random.randint(-5, 5))

        review_rows.append(
            f"({e['employee_id']}, {fmt(rdate)}, {reviewer}, {rating}, {goals_met}, '{comment}', '{period}')"
        )

chunk_insert(
    "INSERT INTO performance_reviews (employee_id, review_date, reviewer_id, rating, goals_met, comments, review_period) VALUES",
    review_rows
)

# ─────────────────────────────────────────────
# 6. ATTRITION
# ─────────────────────────────────────────────
sql("-- ------------------------------------------------------------")
sql("-- ATTRITION (~180 rows)")
sql("-- ------------------------------------------------------------")

exit_reasons = [
    'Better opportunity', 'Salary dissatisfaction', 'Work-life balance',
    'Relocation', 'Personal reasons', 'Career change', 'Manager conflict',
    'Lack of growth', 'Company culture'
]
exit_types = ['Resignation', 'Resignation', 'Resignation', 'Termination', 'Retirement', 'Redundancy']

attrition_rows = []
terminated = [e for e in employees if e['status'] == 'Terminated']

for e in terminated:
    years = round((date(2024, 12, 31) - e['hire_date']).days / 365, 1)
    exit_date = e['hire_date'] + timedelta(days=random.randint(180, int(years * 365) if years > 0.5 else 365))
    if exit_date > date(2024, 12, 31):
        exit_date = date(2024, 11, 30)

    # Plant problem: bad manager's team cites manager conflict more
    if e['manager_id'] == bad_manager_id:
        reason = random.choices(exit_reasons, weights=[3, 8, 8, 3, 3, 3, 40, 25, 7])[0]
        regrettable = 1
    elif e['department_id'] == 1:  # Engineering in general
        reason = random.choices(exit_reasons, weights=[5, 12, 10, 5, 5, 5, 25, 25, 8])[0]
        regrettable = random.choices([0, 1], weights=[40, 60])[0]
    else:
        reason = random.choice(exit_reasons)
        regrettable = random.choices([0, 1], weights=[60, 40])[0]

    # Fix: retirement only for employees aged 55+ at exit date
    age_at_exit = (exit_date - e['birth_date']).days // 365
    if age_at_exit >= 55:
        available_types = ['Resignation', 'Resignation', 'Resignation', 'Termination', 'Retirement', 'Redundancy']
    else:
        available_types = ['Resignation', 'Resignation', 'Resignation', 'Resignation', 'Termination', 'Redundancy']

    exit_type         = random.choice(available_types)
    interview_done    = random.choices([0, 1], weights=[30, 70])[0]
    rehire_eligible   = 0 if exit_type == 'Termination' else random.choices([0, 1], weights=[20, 80])[0]
    actual_years      = round((exit_date - e['hire_date']).days / 365, 1)

    attrition_rows.append(
        f"({e['employee_id']}, {fmt(exit_date)}, '{reason}', '{exit_type}', "
        f"{interview_done}, {regrettable}, {rehire_eligible}, {actual_years})"
    )

chunk_insert(
    "INSERT INTO attrition (employee_id, exit_date, exit_reason, exit_type, exit_interview_done, regrettable, rehire_eligible, years_of_service) VALUES",
    attrition_rows
)

# ─────────────────────────────────────────────
# 7. RECRUITMENT (120 rows)
# ─────────────────────────────────────────────
sql("-- ------------------------------------------------------------")
sql("-- RECRUITMENT (120 rows)")
sql("-- ------------------------------------------------------------")
source_channels = ['LinkedIn', 'Wuzzuf', 'Bayt', 'Referral', 'Agency', 'Company Website']
rec_rows = []
req_id = 1

for dept_id in range(1, 7):
    num_reqs = random.randint(15, 25)
    for _ in range(num_reqs):
        job_id     = random.choice(dept_jobs[dept_id])
        # 20% of requisitions are recent and still Open
        is_open = random.random() < 0.20

        if is_open:
            open_date  = rand_date(date(2024, 6, 1), date(2024, 10, 1))
            status     = 'Open'
            # Still give open reqs a realistic expected close date
            # Engineering open reqs take longer
            if dept_id == 1:
                days_open = random.randint(60, 90)
            elif dept_id == 3:  # HR fills fast
                days_open = random.randint(10, 25)
            else:
                days_open = random.randint(20, 45)
            close_date = open_date + timedelta(days=days_open)
        else:
            open_date  = rand_date(date(2020, 1, 1), date(2024, 5, 1))
            status     = 'Closed'
            # Plant problem: Engineering takes longest to fill
            if dept_id == 1:
                days_open = random.randint(60, 95)
            elif dept_id == 3:  # HR fills fastest
                days_open = random.randint(10, 25)
            elif dept_id == 4:  # Finance moderate
                days_open = random.randint(20, 40)
            else:
                days_open = random.randint(15, 45)
            close_date = open_date + timedelta(days=days_open)

        positions  = random.choices([1, 2, 3], weights=[70, 20, 10])[0]
        filled     = 0 if is_open else positions

        channel    = random.choice(source_channels)
        mgr_id     = dept_manager_map[dept_id]
        recruiter  = dept_manager_map[3]
        close_val  = 'NULL' if is_open else fmt(close_date)

        rec_rows.append(
            f"({req_id}, {job_id}, {dept_id}, {fmt(open_date)}, {close_val}, "
            f"'{status}', {mgr_id}, {recruiter}, {positions}, {filled}, '{channel}')"
        )
        req_id += 1

total_reqs = req_id - 1

chunk_insert(
    "INSERT INTO recruitment (requisition_id, job_id, department_id, open_date, close_date,\n"
    "    status, hiring_manager_id, recruiter_id, positions_needed, filled_positions, source_channel) VALUES",
    rec_rows
)

# ─────────────────────────────────────────────
# 8. CANDIDATES (~600 rows)
# ─────────────────────────────────────────────
sql("-- ------------------------------------------------------------")
sql("-- CANDIDATES (~600 rows)")
sql("-- ------------------------------------------------------------")
stages    = ['Applied', 'Screened', 'Interview', 'Offer', 'Hired', 'Rejected']
outcomes  = ['Hired', 'Rejected', 'Withdrew', 'No Show']
cand_rows = []
cand_id   = 1

# Track which employees came from agency (for attrition plant)
agency_employee_ids = []

hired_emp_iter = iter([e['employee_id'] for e in employees if e['status'] in ('Active', 'Terminated')])

for r_id in range(1, total_reqs + 1):
    num_candidates = random.randint(3, 7)
    for c in range(num_candidates):
        fname   = fake.first_name()
        lname   = fake.last_name()
        email   = fake.email()
        phone   = fake.numerify('+20 1## ### ####')
        app_date = rand_date(date(2020, 1, 1), date(2024, 9, 1))
        channel  = random.choice(source_channels)

        # Plant problem: low offer acceptance from Agency channel
        if channel == 'Agency':
            outcome = random.choices(outcomes, weights=[15, 50, 25, 10])[0]
        else:
            outcome = random.choices(outcomes, weights=[25, 50, 15, 10])[0]

        stage      = 'Hired' if outcome == 'Hired' else random.choice(['Screened', 'Interview', 'Rejected'])
        stage_date = app_date + timedelta(days=random.randint(3, 30))
        offer_amt  = round(random.uniform(2500, 12000), 2) if outcome == 'Hired' else 'NULL'

        if outcome == 'Hired':
            try:
                emp_id_linked = next(hired_emp_iter)
                hired_flag = 1
                if channel == 'Agency':
                    agency_employee_ids.append(emp_id_linked)
            except StopIteration:
                emp_id_linked = 'NULL'
                hired_flag = 0
        else:
            emp_id_linked = 'NULL'
            hired_flag    = 0

        offer_val  = str(offer_amt) if offer_amt != 'NULL' else 'NULL'
        emp_val    = str(emp_id_linked) if emp_id_linked != 'NULL' else 'NULL'

        cand_rows.append(
            f"({cand_id}, {r_id}, '{fname}', '{lname}', '{email}', '{phone}', "
            f"{fmt(app_date)}, '{channel}', '{stage}', {fmt(stage_date)}, "
            f"'{outcome}', {offer_val}, {hired_flag}, {emp_val})"
        )
        cand_id += 1

chunk_insert(
    "INSERT INTO candidates (candidate_id, requisition_id, first_name, last_name, email,\n"
    "    phone, application_date, source_channel, stage, stage_date, outcome, offer_amount, hired_as_employee, employee_id) VALUES",
    cand_rows
)

# ─────────────────────────────────────────────
# Update department manager_ids
# ─────────────────────────────────────────────
sql("-- ------------------------------------------------------------")
sql("-- UPDATE department manager_ids")
sql("-- ------------------------------------------------------------")
for dept_id, mgr_id in dept_manager_map.items():
    sql(f"UPDATE departments SET manager_id = {mgr_id} WHERE department_id = {dept_id};")

sql("\n-- ============================================================")
sql("-- Data generation complete.")
sql(f"-- Employees: 1,000 | Salaries: ~{len(salary_rows)}")
sql(f"-- Reviews: ~{len(review_rows)} | Attrition: {len(attrition_rows)}")
sql(f"-- Recruitment: {total_reqs} | Candidates: ~{cand_id - 1}")
sql("-- ============================================================")

# ─────────────────────────────────────────────
# Write output file
# ─────────────────────────────────────────────
output_path = "/mnt/user-data/outputs/hr_analytics_data.sql"
with open(output_path, "w", encoding="utf-8") as f:
    f.write("\n".join(output_lines))

print(f"✅ Done! File written to: {output_path}")
print(f"   Employees  : 1,000")
print(f"   Salaries   : {len(salary_rows)}")
print(f"   Reviews    : {len(review_rows)}")
print(f"   Attrition  : {len(attrition_rows)}")
print(f"   Requisitions: {total_reqs}")
print(f"   Candidates : {cand_id - 1}")
